# 01-HEADER
# menu
menu:
    home: /
    archive: /archives
    categories: /categories
    tags: /tags
    about: /about
    #gallery: http://gallery.sariay.me/
    gallery: /gallery

# favicon & avtor
# if the value of avtor is false, the 'say' is optional.
favicon: /img/favicon.ico
logo: /img/logo5.png
title: Welcome 

# background_image
# /img/01.jpg
# https://source.unsplash.com/collection/954550/1920x1080
# https://sariay.github.io/Random-img/
# https://annie-header-bg-1253939655.cos.ap-beijing.myqcloud.com/
# May be cause CROS bug!
background_image:
    mode: random #normal or random
    normal_url: /img/1.jpg
    random_max: 110 
    random_url: https://annie-header-bg-1253939655.cos.ap-beijing.myqcloud.com/
    
# show motto
motto:
    enable: true
    
# show current time
# This is only a demo, please go to "https://time.is" to set your city time!
timejs:
    enable: true

# 02-PROLOADER
# animation: spinner, transition or cyclic
preloader:
    enable: true
    animation: spinner

# 03-INDEX
# index-style: pure, cart or poem
index_style: cart

# index_cart_cover
cover: /img/cart_cover.jpg
lazy_image: /img/placeholder.jpg

# 04-POST
# post_relate
relate:
    enable: true
    posts_limit: 10
    posts_excerpt: 120

# post_comment
comment:
    enable: true

gitalk:
    enable: true
    clientID: 'bf19f33d43d567dce87e' 
    clientSecret: '32f473f6f860a8f82ae10fcfd978c83c0954b93f' 
    repo: annie-gitalk 
    owner: Sariay 
    admin: Sariay 
    distractionFreeMode: true
    #去除 more、index.html、?query=123等格式尾部 
    hrefTrimend: '#.*$,\\?.*$,index.html$' 
    
valine: 
    enable: false
    appid: 'DU84u3YWC8In5QjcOvBiDFlo-gzGzoHsz'
    appkey: 'Ae6l2pVhIBRlKbN115rMdn8K'
    placeholder: no any!
    
livere: 
    enable: false
    livere_uid: 'sdd'
    
# post_count
leancloud_count:
    enable: true
    appid: 'dX2cfN1apuSDGy1JIUwKBIA2-gzGzoHsz'
    appkey: 'wzGaywJpxGEhEclcl87rdtHG'
    like_post:
        enable: true
    visit_post:
        enable: true
    topN_post: 
        enable: true #param1 for topN_post
        limit: 10 #param2 for topN_post
busuanzi_count:
    enable: true
baidu_analytics:
    enable: false
    id: 
cnzz_analytics:
    enable: false
    id:
google_analytics:
    enable: false
    id:
tencent_analytics:
    enable: false
    id:

# post_toc
post_toc:
    enable: true
    katelog: true
    
# post_mathJax
mathjax:
  enable: true
  
# post_code
# normal | night | night blue | night bright | night eighties
highlight_theme: night bright
code_copy:
    enable: true

# post_excerpt for index page
excerpt_cart: 80
excerpt_pure: 300   
excerpt_link: true

# post_share
share:
    enable: true
# 注意浏览器的内容拦截插件
#https://www.addthis.com/
addThis:
    enable: false
    id: ra-5c7a56e7cb0ee41e
#http://share.baidu.com/code
baiduShare: 
    enable: false
    style: button # you can add slide style!
#https://www.sharethis.com/onboarding-cms/    
shareThis:
    enable: false
    id: 5c862b0996ec580017cff2d3
    
#https://github.com/overtrue/share.js
socialShare:
    enable: true

# 05-FOOTER
# social
social:
    github:
        url: http://github.com/
        icon: fa fa-github
    weibo:
        url: http://github.com/
        icon: fa fa-weibo    
    pinterest: 
        url: http://github.com/
        icon: fa fa-pinterest
    instagram:
        url: http://github.com/
        icon: fa fa-instagram
    twitter:
        url: http://github.com/
        icon: fa fa-twitter
    rss: 
        url: /atom.xml
        icon: fa fa-rss

# copyright  
since: 2017
cotent_author: Sariay

# 06-OTHERS

# gallery page
# format: natural or square
gallery_format: natural
# one time to load 4 rows or other count, 0 to load img automatically when scrolling.(0,1,2,3,4,5,6......)
gallery_limit: 0
# data url
gallery_data: plugin/gallerypage/data.json

# Local search
# Dependencies: https://github.com/flashlab/hexo-generator-search
local_search:
    enable: true
    # if auto, trigger search by changing input
    # if manual, trigger search by pressing enter key or search button
    trigger: auto
    # show top n results per article, show all results by setting to -1
    top_n_per_article: 2

#when click, emerge heart
love:
    enable: true

#totop
totop:
    enable: true